// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: google/monitoring/dashboard/v1/drilldowns.proto

package com.google.monitoring.dashboard.v1;

public final class DrilldownsProto {
  private DrilldownsProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n/google/monitoring/dashboard/v1/drilldo" +
      "wns.proto\022\036google.monitoring.dashboard.v" +
      "1\032+google/monitoring/dashboard/v1/common" +
      ".protoB\322\001\n\"com.google.monitoring.dashboa" +
      "rd.v1B\017DrilldownsProtoP\001ZGgoogle.golang." +
      "org/genproto/googleapis/monitoring/dashb" +
      "oard/v1;dashboard\312\002$Google\\Cloud\\Monitor" +
      "ing\\Dashboard\\V1\352\002(Google::Cloud::Monito" +
      "ring::Dashboard::V1b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.google.monitoring.dashboard.v1.CommonProto.getDescriptor(),
        });
    com.google.monitoring.dashboard.v1.CommonProto.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
